# Generated by Django 5.2.10 on 2026-02-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_miscellaneouscharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
